# Use official ASP.NET image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY KabeloWeb/ ./KabeloWeb/
WORKDIR /src/KabeloWeb

RUN dotnet restore "KabeloWeb.csproj"
RUN dotnet publish "KabeloWeb.csproj" -c Release -o /app/publish

# Run stage
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:$PORT

ENTRYPOINT ["dotnet", "KabeloWeb.dll"]